[build]
  command = "npm run build"  # The command to generate the build artifacts
  publish = "/opt/build/repo/dist"  # Specify the correct publish directory

[build.environment]
  NODE_ENV = "production"
